mylist = ["Iowa", "Idaho", "Wisconsin", "Kansas", "Ohio"]
print(len(mylist))
print(mylist[2])
print(mylist[1:])
print(mylist[-1])
print(mylist.index("Ohio"))
print(mylist)
print(mylist.pop(1))
print(mylist)

mylist.sort(reverse = True)
print(mylist)
print ("@@@@@@@")
mylist.append("Indiana")
print(mylist)